version: '3.8'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER={}
